### ISSUE TITLE
作者大大更新一下吧，插件不能用了

### ISSUE THREAD

**Issue by waves-dylan** [YS-Wong/Article-Unlocker#2]
作者大大更新一下吧，插件不能用了

**Comment by easonwong-de** [comment]
若是部分文章 ([例](https://theinitium.com/article/20230331-hongkong-combating-false-information/)) 仍得以解鎖，部分無法解鎖，則應是此 add-on 未能找到文章原文，此時此 add-on 的 Developer Tools 的控制台裏將出現 `Too many attempts, giving up.` 提示。

<img width="782" alt="Screenshot 2023-03-31 at 16 34 57" src="https://user-images.githubusercontent.com/16183548/229150450-9b04f71e-f748-48cf-bc5c-e784ebe41d75.png">

此 add-on 依賴 Telegram bot [Article reader|Статей читалка](https://t.me/chotamreaderbot) 產生的內容。只要有人曾用該 bot 解鎖文章，此 add-on 即可在多數情況下獲取文章內容。

若是「免費支持」按鈕從不出現，則希望閣下可以前往 `about:debugging#/runtime/this-firefox`，在 Article Unlocker 處點選「Inspect」。若閣下可對控制台錯誤訊息進行熒幕擷圖，這將對 debug 幫助甚大。
